apiVersion: apps/v1
kind: Deployment
metadata:
  name: scdf-server
  labels:
    app: scdf-server
spec:
  selector:
    matchLabels:
      app: scdf-server
  replicas: 1
  template:
    metadata:
      labels:
        app: scdf-server
    spec:
      containers:
      - name: scdf-server
        image: infydtr.ad.infosys.com/maunika_tamire/spring-cloud-dataflow-server:2.5.3.RELEASE
        imagePullPolicy: Always
        volumeMounts:
          - name: config
            mountPath: /config
            readOnly: true
          - name: database
            mountPath: /etc/secrets/database
            readOnly: true
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /management/health
            port: 80
          initialDelaySeconds: 45
        readinessProbe:
          httpGet:
            path: /management/info
            port: 80
          initialDelaySeconds: 45
        resources:
          limits:
            cpu: 1.0
            memory: 2048Mi
          requests:
            cpu: 0.5
            memory: 1024Mi
        env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        - name: SERVER_PORT
          value: '80'
        - name: SPRING_CLOUD_CONFIG_ENABLED
          value: 'false'
        - name: SPRING_CLOUD_DATAFLOW_FEATURES_ANALYTICS_ENABLED
          value: 'true'
        - name: SPRING_CLOUD_DATAFLOW_FEATURES_SCHEDULES_ENABLED
          value: 'true'
        - name: SPRING_CLOUD_DATAFLOW_TASK_COMPOSED_TASK_RUNNER_URI
          value: 'docker://springcloud/spring-cloud-dataflow-composed-task-runner:2.6.1'
        - name: SPRING_CLOUD_KUBERNETES_CONFIG_ENABLE_API
          value: 'false'
        - name: SPRING_CLOUD_KUBERNETES_SECRETS_ENABLE_API
          value: 'false'
        - name: SPRING_CLOUD_KUBERNETES_SECRETS_PATHS
          value: /etc/secrets
        - name: SPRING_CLOUD_DATAFLOW_SERVER_URI
          value: 'http://${SCDF_SERVER_SERVICE_HOST}:${SCDF_SERVER_SERVICE_PORT}'
          # Provide the Skipper service location
        - name: SPRING_CLOUD_SKIPPER_CLIENT_SERVER_URI
          value: 'http://${SKIPPER_SERVICE_HOST}:${SKIPPER_SERVICE_PORT}/api'
          # Add Maven repo for metadata artifact resolution for all stream apps
        - name: SPRING_APPLICATION_JSON
          value: "{ \"maven\": { \"local-repository\": null, \"remote-repositories\": { \"repo1\": { \"url\": \"https://repo.spring.io/libs-snapshot\"} } } }"
        - name: SPRING_CLOUD_DATAFLOW_SECURITY_CF_USE_KEYCLOAK
          value: "true"
        - name: SECURITY_OAUTH2_CLIENT_CLIENT_ID
          value: "dataflow"
        - name: SECURITY_OAUTH2_CLIENT_CLIENT_SECRET
          value: "501455ac-f7f9-4cef-bbea-26ceb476e1cc"
        - name: SECURITY_OAUTH2_CLIENT_ACCESS_TOKEN_URI
          value: 'http://10.68.92.118:8080/auth/realms/scdf/protocol/openid-connect/token'
        - name: SECURITY_OAUTH2_CLIENT_USER_AUTHORIZATION_URI
          value: 'http://10.68.92.118:8080/auth/realms/scdf/protocol/openid-connect/auth'
        - name: SECURITY_OAUTH2_RESOURCE_USER_INFO_URI
          value: 'http://10.68.92.118:8080/auth/realms/scdf/protocol/openid-connect/userinfo'
        - name: SECURITY_OAUTH2_RESOURCE_TOKEN_INFO_URI
          value: 'http://10.68.92.118:8080/auth/realms/scdf/protocol/openid-connect/token/introspect'
        - name : spring.cloud.dataflow.security.authorization.permit-all-paths
          value:  "/management/**,/actuator/**,/authenticate,/security/info,/assets/**,/dashboard/logout-success-oauth.html" 
      initContainers:
      - name: init-mysql-wait
        image: infydtr.ad.infosys.com/maunika_tamire/busybox:latest
        command: ['sh', '-c', 'until nc -w3 -z mysql 3306; do echo waiting for mysql; sleep 3; done;']
      serviceAccountName: scdf-sa
      volumes:
        - name: config
          configMap:
            name: scdf-server
            items:
            - key: application.yaml
              path: application.yaml
        - name: database
          secret:
            secretName: mysql
